# Generated by Django 5.2.5 on 2025-09-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0003_course_delete_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subjects_tutor',
            new_name='keywords',
        ),
        migrations.RemoveField(
            model_name='course',
            name='curse',
        ),
        migrations.RemoveField(
            model_name='course',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/'),
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subjects_tutor', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='step/')),
                ('slug', models.SlugField(unique=True)),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
